name: Android emulator
on: [push]

jobs:
  build-containers:
    name: Build ${{ matrix.config.platform }} Container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { platform: linux/arm64, tag: devel-arm64 }

    steps:

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      #      - name: Build Docker Image
      #        run: docker build --no-cache -t android-build-arm64 .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.config.platform }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bioc-with-tinytex:${{ matrix.config.tag }}