name: Github-hosted Runner
on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [33]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Java 11 for instrumented tests
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      #      - name: create AVD and generate snapshot for caching
      #        if: steps.avd-cache.outputs.cache-hit != 'true'
      #        uses: reactivecircus/android-emulator-runner@v2
      #        with:
      #          api-level: ${{ matrix.api-level }}
      #          force-avd-creation: false
      #          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #          disable-animations: false
      #          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: x86_64
          profile: pixel_2
          ram-size: 4096M
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest --stacktrace