name: New github hosted runner
on: [push]

jobs:
  drive_android:
    runs-on: macos-latest-xlarge
    strategy:
      matrix:
        api-level: [33]
        target: [playstore]
    steps:
      - uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: ls -al /Users/

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: arm64-v8a
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          channel: canary
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          arch: arm64-v8a
          profile: Nexus 6
          #          ram-size: 2048M
          api-level: ${{ matrix.api-level }}
          #          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          #          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest --stacktrace